defmodule Playdate.Repo.Migrations.PersonBelongsToPerson do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:people) do
      modify(:birthdate, :map, null: true)

      add(
        :user_id,
        references(:people,
          column: :id,
          name: "people_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:people, "people_user_id_fkey"))

    alter table(:people) do
      remove(:user_id)
      modify(:birthdate, :map, null: false)
    end
  end
end
