defmodule Playdate.Repo.Migrations.AddBirthdate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:people) do
      add(:birthdate, :map)
    end
  end

  def down do
    alter table(:people) do
      remove(:birthdate)
    end
  end
end
